name: Build and Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Test
          - os: macos-latest
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Test
          - os: windows-latest
            build_type: Test

    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        if: runner.os == 'Windows'
        run: choco install ninja -y

      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
        with:
          arch: x64

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
          echo "install-prefix=${{ github.workspace }}" >> "$GITHUB_OUTPUT"

      - name: Configure CMake (Unix)
        if: runner.os != 'Windows'
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}

      - name: Configure CMake (Windows MSVC)
        if: runner.os == 'Windows'
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_C_COMPILER=cl
          -DCMAKE_CXX_COMPILER=cl

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Install
        run: cmake --install ${{ steps.strings.outputs.build-output-dir }} --prefix ${{ steps.strings.outputs.install-prefix }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest -C ${{ matrix.build_type }}
